### ISSUE TITLE
Support for native Kubernetes leases

### ISSUE THREAD

**Issue by antoninguyot** [apache/pekko-management#217]
Kubernetes offers a native `Lease` object in the `coordination.k8s.io` API group, which seems to very much ressemble the `Lease` object offered by Pekko in `pekko.apache.org`. Switching to use the native `Lease` object would have some benefits, such as not having to install and maintain a custom CRD, which often makes using leases impossible in tightly controlled Kubernetes environments. Additionally, it is encouraged by the [Kubernetes documentation](https://kubernetes.io/docs/concepts/architecture/leases/#custom-workload).

Do you see any particular difficulty in implementing this in Pekko ? We could help with the implementation if needed so

**Comment by pjfanning** [comment]
@antoninguyot Thanks for raising this. I am not a Kubernetes expert but it does seem like Kubernetes native leases would be very useful to support. It would be great if you or your team could look at doing a basic implementation that has similar capabilities to the existing CRD based lease. https://nightlies.apache.org/pekko/docs/pekko-management/main-snapshot/docs/kubernetes-lease.html

Pekko community members will review anything that you submit.

**Comment by antoninguyot** [comment]
@pjfanning Perfect, will look at it over the next week

**Comment by pjfanning** [comment]
#218 #236 merged
