### ISSUE TITLE
Kubernetes Namespace Service Discovery

### ISSUE THREAD

**Issue by shakeeb-upstart** [apache/pekko-management#311]
Hi, can we add a new helper method in the "KubernetesApiServiceDiscovery" class, to lookup services in a different namespace than the default provided in the configurations. I am trying to lookup a service that's in a different Kubernetes namespace.

**Comment by raboof** [comment]
That makes sense to me. Perhaps we could add a constructor to `KubernetesApiServiceDiscovery` that you can provide your own `org.apache.pekko.discovery.kubernetes.Settings`-like object to instead of relying on the one from the `system` - would that work in your case?

**Comment by shakeeb-upstart** [comment]
Yeah that would work, I was only thinking of `podNamespace` and overloading it to a separate method, but having `Settings `will give us ability to configure the other options as well

**Comment by shakeeb-upstart** [comment]
I cannot make changes to the constructor, It has to abide by the `ServiceDiscovery `constructor for 'DynamicAccess'.

**Comment by raboof** [comment]
would it be possible to have two constructors, one like the original for 'DynamicAccess' and one that takes a custom `Settings`?

**Comment by shakeeb-upstart** [comment]
I tried with defining 'apply' method in the companion object but it doesn't work.

**Comment by raboof** [comment]
> I tried with defining 'apply' method in the companion object but it doesn't work.

Perhaps if you add this to the class instead of creating an apply method?

```
  def this(system: ActorSystem) = {
    this(Settings(system))(system)
  }
```

**Comment by shakeeb-upstart** [comment]
Yup that worked
