### ISSUE TITLE
Supporting to fetch pods in Kubernetes based discovery with `gzip` compression

### ISSUE THREAD

**Issue by thjaeckle** [apache/pekko-management#335]
Hello Pekko maintainers.

We currently face an issue where the response of Kubernete's HTTP API is >1 MB (as we e.g. have 15 Pekko pods in our cluster and the `api/v1/namespaces/$NAMESPACE/pods` endpoint also returns all environment variables of all pods - which can become quite big.

So I looked at options and found that the [Kubernetes HTTP API supports compression for responses](https://kubernetes.io/docs/reference/using-api/api-concepts/#response-compression) since 1.16, simply by setting the HTTP header `Accept-Encoding: gzip`.

In our case that brings down the response size a lot:
```
-rw-r--r--. 1 ubuntu ubuntu  112709 Oct 15 13:59 out2.tar.gz
-rw-r--r--. 1 ubuntu ubuntu 1056800 Oct 15 13:37 out.txt
```

Would you accept a contribution to make gzip compression (and decoding) configurable at this place:
https://github.com/apache/pekko-management/blob/5703a2a0459f941c22b9f2fa768c36f33f727703/discovery-kubernetes-api/src/main/scala/org/apache/pekko/discovery/kubernetes/KubernetesApiServiceDiscovery.scala#L229-L240

I would be happy to contribute that.

Our alternative would be to increase the default payload limits of http responses to greater 1 MB (which is the default for pekko-http I think) - however for the future I see potential problems with that, if our cluster grows in number of pods.

**Comment by thjaeckle** [comment]
I assume that the 1MB default is configured here as `max-chunk-size`:
https://github.com/apache/pekko-http/blob/91315b324e7ca45c9a4892b09a0609bb69afa391/http-core/src/main/resources/reference.conf#L693C5-L693C19

**Comment by pjfanning** [comment]
Supporting gzip compression seems useful.
With the max-chunk-size, I suggest trying out different values but it seems plausible that this setting is in play.

**Comment by pjfanning** [comment]
https://pekko.apache.org/docs/pekko-http/1.1/common/encoding.html may be of interest
